name: Keep Render Alive

on:
  schedule:
    # Chạy mỗi 7 phút (theo giờ UTC)
    - cron: "*/7 * * * *"
  workflow_dispatch: # Cho phép bấm nút chạy tay

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Endpoint
        run: |
          echo "Pinging Render server..."
          curl -s --retry 3 --max-time 30 https://bankingnoti.onrender.com/health || echo "Server might still be waking up"
